{
 "title": "Infiniband Fabric Health",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "IB switch unhealthy PSUs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "infiniband:switch_power_supply_dc_power_status_info{status!=\"OK\"} == 1",
     "legendFormat": "{{switch}} psu{{psu}} {{status}}"
    }
   ]
  },
  {
   "title": "IB switch unhealthy fans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "infiniband:switch_fan_status_info{status!=\"OK\"}",
     "legendFormat": "{{switch}} fan {{status}}"
    }
   ]
  },
  {
   "title": "IB switch port link down",
   "type": "timeseries",
   "description": "These typically happen when a node is rebooted.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "infiniband:switch_port_link_downed:delta5m>0",
     "legendFormat": "{{switch}} p{{port}} to {{uplink}} p{{uplink_port}}"
    }
   ]
  },
  {
   "title": "IB switch/host port symbol errors",
   "type": "timeseries",
   "description": "A continuous stream of these indicates an unhealthy link and possibly a bad cable",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "infiniband:switch_port_symbol_error:delta5m>0",
     "legendFormat": "{{switch}} p{{port}} to {{uplink}} p{{uplink_port}}"
    },
    {
     "expr": "delta(node_infiniband_symbol_error_total[5m])>0",
     "legendFormat": "{{host}} p{{port}}"
    }
   ]
  },
  {
   "title": "IB switch port transmit packets discarded",
   "type": "timeseries",
   "description": "Typically indicates that the link has gone down on the uplink/node side, so these will usually (but not always) correlate to a link going down because the node on the other end rebooted.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "infiniband:switch_port_transmit_discards:delta5m>0",
     "legendFormat": "{{switch}} p{{port}} to {{uplink}} p{{uplink_port}}"
    }
   ]
  },
  { "title": "IB switch port BER", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 } },
  {
   "title": "IB switch port receive remote physical errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "infiniband:switch_port_receive_remote_physical_errors:delta5m>0",
     "legendFormat": "{{switch}} p{{port}} to {{uplink}} p{{uplink_port}}"
    }
   ]
  },
  {
   "title": "IB switch port local link integrity errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "infiniband:switch_port_local_link_integrity_errors:delta5m>0",
     "legendFormat": "{{switch}} p{{port}} to {{uplink}} p{{uplink_port}}"
    }
   ]
  }
 ]
}