{
 "title": "Infiniband Fabric Performance",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Most congested IB switches",
   "type": "timeseries",
   "description": "More than 1e12 for more than an hour indicates congestion",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "(sum by (switch) (infiniband:switch_port_transmit_wait:delta5m>0))>2*10^12",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Most congested IB links",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "topk(20, infiniband:switch_port_transmit_wait:delta5m > 5*10^10)",
     "legendFormat": "{{switch}} p{{port}} to {{uplink}} p{{uplink_port}}"
    }
   ]
  },
  {
   "title": "Most active IB switches by bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(20, sum by (switch) (infiniband:switch_port_receive_data_bytes:irate5m>0))",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Most active IB links by bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(20, infiniband:switch_port_receive_data_bytes:irate5m>0)",
     "legendFormat": "{{uplink}} p{{uplink_port}} to {{switch}} p{{port}}"
    }
   ]
  },
  {
   "title": "Most active IB switches by packet rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(20, sum by (switch) (infiniband:switch_port_receive_packets:irate5m))",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Most active IB links by packet rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(20, infiniband:switch_port_receive_packets:irate5m)",
     "legendFormat": "{{uplink}} p{{uplink_port}} to {{switch}} p{{port}}"
    }
   ]
  }
 ]
}